[2023-07-09 08:36:52,083] ERROR log_exception() L1449 Exception on /curso/matricula [POST] - call_trace=C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: curso.cpf

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "C:\Users\gipri\PycharmProjects\university\app.py", line 132, in add_matricula
    session.commit()
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\orm\session.py", line 829, in commit
    self._prepare_impl()
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\orm\session.py", line 808, in _prepare_impl
    self.session.flush()
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\orm\session.py", line 3386, in flush
    self._flush(objects)
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\orm\session.py", line 3526, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\orm\session.py", line 3486, in _flush
    flush_context.execute()
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 456, in execute
    rec.execute(self)
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: curso.cpf
[SQL: INSERT INTO curso (cpf, codigo_curso, curso, codigo_disc, disciplina, creditos, data_matricula, aluno_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('123.332.434-20', 2276544, 'psicologia', 22222, 'hospitalar', 8, '2023-07-09 08:29:13.892704', 1)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2023-07-09 08:36:52,083] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 08:36:52] "[35m[1mPOST /curso/matricula HTTP/1.1[0m" 500 - - call_trace=C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-07-09 08:38:52,020] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.28.49:5000 (Press CTRL+C to quit) - call_trace=C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-07-09 08:39:03,501] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 08:39:03] "POST /aluno/cadastro HTTP/1.1" 200 - - call_trace=C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-07-09 08:39:10,748] WARNING add_matricula() L128  Erro ao matricular aluno '123.332.434-20', Aluno não encontrado na base :/ - call_trace=C:\Users\gipri\PycharmProjects\university\app.py L128 
[2023-07-09 08:39:10,748] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 08:39:10] "[33mPOST /curso/matricula HTTP/1.1[0m" 404 - - call_trace=C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-07-09 08:39:46,328] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 08:39:46] "POST /curso/matricula HTTP/1.1" 200 - - call_trace=C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-07-09 08:39:48,580] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 08:39:48] "POST /curso/matricula HTTP/1.1" 200 - - call_trace=C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-07-09 08:48:13,603] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.28.49:5000 (Press CTRL+C to quit) - call_trace=C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-07-09 08:48:26,492] WARNING add_matricula() L133  Erro ao matricular aluno '222.112.323.54', Aluno já matriculado:/ - call_trace=C:\Users\gipri\PycharmProjects\university\app.py L133 
[2023-07-09 08:48:26,492] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 08:48:26] "[33mPOST /curso/matricula HTTP/1.1[0m" 404 - - call_trace=C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-07-09 08:48:49,296] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 08:48:49] "GET /aluno/listagem HTTP/1.1" 200 - - call_trace=C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-07-09 08:50:11,885] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 08:50:11] "GET /aluno/busca_CPF?cpf=222.112.323.54&nome=Luciana%20da%20Silva%20Santos HTTP/1.1" 200 - - call_trace=C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-07-09 08:51:05,473] WARNING add_matricula() L133  Erro ao matricular aluno '222.112.323.54', Aluno já matriculado:/ - call_trace=C:\Users\gipri\PycharmProjects\university\app.py L133 
[2023-07-09 08:51:05,473] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 08:51:05] "[33mPOST /curso/matricula HTTP/1.1[0m" 404 - - call_trace=C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-07-09 08:52:11,922] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.28.49:5000 (Press CTRL+C to quit) - call_trace=C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-07-09 08:52:17,130] WARNING add_matricula() L133  Erro ao matricular aluno '222.112.323.54', Aluno já matriculado:/ - call_trace=C:\Users\gipri\PycharmProjects\university\app.py L133 
[2023-07-09 08:52:17,130] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 08:52:17] "[31m[1mPOST /curso/matricula HTTP/1.1[0m" 409 - - call_trace=C:\Users\gipri\PycharmProjects\university\venv\lib\site-packages\werkzeug\_internal.py L224 
